# Generated by Django 5.2 on 2025-04-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConteoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('encendido', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Piston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conteo_activaciones', models.PositiveIntegerField(default=0)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='SensorOptico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conteo_detecciones', models.PositiveIntegerField(default=0)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='SensorPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_objetivo', models.FloatField()),
                ('peso_actual', models.FloatField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina')),
            ],
        ),
    ]
