# Generated by Django 5.2 on 2025-04-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteoproduccion',
            options={'verbose_name': 'Conteo de producción', 'verbose_name_plural': 'Conteos de producción'},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='motor',
            options={'verbose_name': 'Motor', 'verbose_name_plural': 'Motores'},
        ),
        migrations.AlterModelOptions(
            name='piston',
            options={'verbose_name': 'Pistón', 'verbose_name_plural': 'Pistones'},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='sensoroptico',
            options={'verbose_name': 'Sensor óptico', 'verbose_name_plural': 'Sensores ópticos'},
        ),
        migrations.AlterModelOptions(
            name='sensorpeso',
            options={'verbose_name': 'Sensor de peso', 'verbose_name_plural': 'Sensores de peso'},
        ),
    ]
