# Generated by Django 5.2 on 2025-04-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maquina_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(blank=True, max_length=100)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='core.maquina')),
            ],
            options={
                'verbose_name': 'Historial de Producción',
                'verbose_name_plural': 'Historiales de Producción',
            },
        ),
    ]
