# Generated by Django 5.2 on 2025-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historialproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'señal',
                'verbose_name_plural': 'señales',
                'ordering': ['id'],
            },
        ),
    ]
