# Generated by Django 5.2 on 2025-05-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entrada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='senales',
        ),
    ]
