# Generated by Django 5.2 on 2025-05-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_entrada_senales'),
    ]

    operations = [
        migrations.AddField(
            model_name='senales',
            name='id_senal',
            field=models.IntegerField(default=-1, verbose_name='indice'),
        ),
    ]
