# Generated by Django 5.2 on 2025-05-06 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMachineAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Solo lectura')], default='viewer', max_length=10)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinas', models.ManyToManyField(blank=True, through='usuarios.UserMachineAccess', to='usuarios.maquina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermachineaccess',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='usermachineaccess',
            unique_together={('profile', 'maquina')},
        ),
    ]
