# Generated by Django 5.2 on 2025-05-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historialproduccion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachineaccess',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquina'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maquinas',
            field=models.ManyToManyField(blank=True, through='usuarios.UserMachineAccess', to='core.maquina'),
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
    ]
